// Generated by CoffeeScript 1.10.0
(function() {
  (function(consts, requests, omi) {
    var cloneAbove, createTimestampPicker, findDuplicate, getGroups, notifyErrorOn, readValues, resetInfoItemForm, updateOdf;
    var groupUnderEdit;

    notifyErrorOn = function(jqElement, errorMsg) {
      return jqElement.tooltip({
        placement: "top",
        title: errorMsg
      }).focus().on('input', function() {
        return $(this).tooltip('destroy').closest('.form-group').removeClass('has-error');
      }).closest('.form-group').addClass('has-error');
    };
    consts.afterJquery(function() {
      consts.groupItemDialog = $('#newGroupItem');
      consts.groupItemForm = consts.groupItemDialog.find('form');
      consts.originalGroupItemForm = consts.groupItemForm.clone();
      consts.groupItemDialog.on('hide.bs.modal', function() {
        return resetGroupItemForm();
      });
      $('#newGroupItem').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var action = button.data('action');

        if (action == "edit") {

          $("#newGroupItemLabel").text("Edit Group");
          var selectedGroup = $("#groupsSelect").chosen().val();
          var currentGroups = WebOmi.formLogic.readedGroups['groups'];
          if (currentGroups != null) {
            for (var i=0;i<currentGroups.length;i++) {
              // console.log("Cur[i]:"+currentGroups[i].id +"/Sel:"+selectedGroup);
              if (currentGroups[i].id == selectedGroup) {
                groupUnderEdit = currentGroups[i];

                console.log("Selected group:"+JSON.stringify(groupUnderEdit));

                $("#groupItemName").val(groupUnderEdit.name);
                $("#addUsersSelect").val(groupUnderEdit.values).trigger("chosen:updated");
                break;
              }
            }
          }
        } else {
          $("#newGroupItemLabel").text("New Group");
        }
      });
      //resetGroupItemForm();
      consts.groupItemDialog.find('#newGroupItemSubmit').on('click', function() {
        var infoitemData;
        infoitemData = readValues();
        return updateGroups(infoitemData);
      });
    });

    readValues = function() {
      var results;
      results = {};
      results["name"] = $("#groupItemName").val();
      results.values = $("#addUsersSelect").chosen().val();
      if (results.values == null) {
        results.values = [];
      }
      if (groupUnderEdit != null) {
        results["id"] = groupUnderEdit["id"];
        groupUnderEdit = null;
      }
      // console.log("Creating new group:" + JSON.stringify(results));
      return results;
    };

    updateGroups = function(newGroupItem) {
      if (newGroupItem["name"].length < 1)
      {
        notifyErrorOn($('#groupItemName'),"Wrong name for new group");
      } else {

        WebOmi.formLogic.updateGroups(newGroupItem);
        consts.groupItemDialog.modal('hide');
      }
    };
    return resetGroupItemForm = function() {
      $('#groupItemName').val('');
      $('#addUsersSelect').val('').trigger('chosen:updated');

    };
  })(WebOmi.consts, WebOmi.requests, WebOmi.omi);

}).call(this);
